# Generated by Django 4.0.1 on 2022-02-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book1',
            name='is_active',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
