# Generated by Django 4.0.1 on 2022-02-01 17:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0002_book1_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book1',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
